name: IaC Scan

on:
  pull_request:
    paths:
      - 'infra/**'
  push:
    branches: [ main ]

jobs:
  tfsec-checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tfsec
        run: |
          sudo curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install.sh | bash

      - name: Run tfsec
        run: tfsec infra/terraform || exit 0

      - name: Install checkov
        run: pip install checkov

      - name: Run checkov
        run: checkov -d infra/terraform || exit 0
